dist: xenial
language: python
python:
  - 3.9
  - 3.8
  - 3.7
  - 3.6
env:
  - TOX_SKIP_ENV=".*djangomaster.*"
  - TOX_SKIP_ENV=".*django[^m].*"
matrix:
  allow_failures:
    - env: TOX_SKIP_ENV=".*django[^m].*"
script: tox
notifications:
  email: false
install:
  - pip install tox
